let cards = [
    {
        title: "ARM",
        description:
            "ARM architecture is a popular processor architecture used in a variety of devices, as smartphones, laptops, and embedded systems. It's designed to be energy-efficient, fast, and scalable, making it an excellent choice for different applications. The workshop includes arm architecture, RCC clock, interrupt, DMA, and more. By the end, you will have an excellent understanding of the STM32F103 microcontroller and its capabilities.",
        objectives: [
            "By the end of this course, you will have a thorough understanding of the STM32F103 microcontroller and its capabilities. You will be able to confidently design and develop embedded systems using arm architecture unlocking its full potential and taking your skills to the next level.",
        ],
        prerequisites: [
            "C/C++ development experience is a must!",
            "Embedded C and dealing with the compilation process is a must",
            "Dealing with any micro-controller is a must",
            "Basic knowledge of Digital electronics.",
        ],
        content: [
            "ARM Architecture",
            "RCC peripheral",
            "GPIO Peripheral",
            "NVIC Peripheral",
            "EXTI",
            "Systick",
            "UART",
            "CAN",
            "LIN",
            "DMA",
        ],
        duration_in_sessions: 12,
        sessions_per_week: 3,
        start_date: new Date(2024, 8, 1),
        location: "Abdo Basha",
        season: "Summer 2024",
        state: "not-started",
    },
    {
        title: "AVR",
        description:
            "AVR microcontrollers are widely used in a variety of applications, from simple DIY projects to complex industrial systems. You will learn topics including Embedded Systems, module drivers, DIO, timers, ADC, communication protocols, and more By the end of this course, Join us to build a solid understanding of how to work with AVR microcontrollers and design your embedded systems using them. So let's dive in and start mastering AVR microcontrollers!",
        objectives: [
            "By the end of the course you will know the concepts of Embedded Systems and get skilled in writing module drivers to interface with any MCU that will make you compatible to go throw embedded track with many embedded system companies.",
        ],
        prerequisites: [
            "Knowledge of C language is a MUST.",
            "Good knowledge of Embedded C",
            "Basic knowledge of Digital electronics.",
        ],
        content: [
            "Intro to Embedded Systems.",
            "Interfacing (GPIO & 7 Segment Display)",
            "AVR Interrupts",
            "AVR Timers",
            "ADC",
            "External Interfacing (LCD & Keypad)",
            "Communication Protocols (UART, SPI and I2C)",
        ],
        duration_in_sessions: 12,
        sessions_per_week: 3,
        start_date: new Date(2024, 8, 1),
        location: "Abdo Basha",
        season: "Summer 2024",
        state: "not-started",
    },
    {
        title: "C Programming",
        description:
            "Operating systems, games, and mobile apps are all made with the help of the robust and popular programming language C. You will learn topics including variables, data types, operators, control flow, functions, arrays, pointers, memory allocation, data structure, and more. Join us to build a strong foundation in C programming and take your skills to the next level.",
        objectives: [
            "This course will give you a strong foundation in C programming and embedded C, regardless of your level of programming experience. You'll have a head start understanding the topics of this workshop if you have a basic understanding of any programming language.",
        ],
        prerequisites: [
            "Logic number system (0,1)",
            "Background in any programming language",
        ],
        content: [
            "Introduction to the C language and Embedded C (Variables, data types, part of data modifiers, I/O ) ",
            "C Operators &Flow Control (if conditions and loops)",
            "Function ",
            "Arrays  ",
            "String  ",
            "Pointer  ",
            "Dynamic Memory Allocation  ",
            "Struct, Union, and Enum ",
            "Memory [Data modifiers and visibility Modifiers, Memory Layout(.bss,.data),Files in C ] ",
            "Preprocessor directive, toolchain",
            "Data Structure",
        ],
        duration_in_sessions: 12,
        sessions_per_week: 3,
        start_date: new Date(2024, 8, 1),
        location: "Abdo Basha",
        season: "Summer 2024",
        state: "not-started",
    },
    {
        title: "Cybersecurity",
        description:
            "Welcome to our Cybersecurity Workshop! In today's digital age, understanding and implementing cybersecurity is crucial for protecting sensitive information and ensuring business continuity. This workshop will provide a comprehensive introduction to the field, covering key concepts such as the importance and objectives of cybersecurity, common threats and vulnerabilities, and essential practices in network and web security.\n\n You will learn about different roles in cybersecurity, types of malware and social engineering attacks, network security essentials like firewalls and encryption, and the fundamentals of penetration testing. By the end of this workshop, you will have the foundational knowledge needed to protect both personal and professional digital environments from cyber threats.",
        prerequisites: [
            "No prerequisites are required.",
        ],
        content: [
            "Introduction to Cybersecurity",
            "Threats, Attacks, and Vulnerabilities",
            "Introduction to Network Security",
            "Web security",
            "Introduction to Penetration Testing",
        ],
        duration_in_sessions: 6,
        sessions_per_week: 2,
        start_date: new Date(2024, 8, 1),
        location: "Abdo Basha",
        season: "Summer 2024",
        state: "not-started",
    },
    {
        title: "ReactJS",
        description:
            "In this workshop, you will have the opportunity to dive deep into the world of React and see how it can be used to develop web applications. You will learn how to build interactive and dynamic user interfaces, integrate with APIs, and much more. Some examples of popular web applications built with React include Facebook, Instagram, and Netflix.",
        objectives: [
            "Build and deploy a React application.",
            "Use JSX to build complex user interfaces.",
            "Manage state in React applications using hooks.",
            "Understand how to handle user input and events in React.",
            "Use React to work with data from APIs.",
            "Make your own web application as a final project.",
        ],
        prerequisites: [
            "A basic understanding of HTML, CSS, and JavaScript",
            "Familiarity with modern JavaScript features, such as arrow functions and destructuring",
            "Experience with a code editor such as VS Code or Sublime Text",
        ],
        content: [
            "Introduction to React",
            "Building a Simple React Application",
            "Managing State in React",
            "Handling User Input and Events",
            "Working with Data from APIs",
            "Testing React Applications",
        ],
        duration_in_sessions: 6,
        sessions_per_week: 2,
        start_date: new Date(2024, 8, 1),
        location: "Abdo Basha",
        season: "Summer 2024",
        state: "not-started",
    },
];

export default cards;
